import 'dotenv/config';
import { PrismaClient, AdminRole } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import * as bcrypt from 'bcryptjs';

// Mirrors src/prisma/prisma.service.ts — Prisma 7 with @prisma/adapter-pg
// requires the driver adapter to be passed explicitly.
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

/**
 * Idempotent: creates exactly one SUPER_ADMIN AdminUser if none exists yet
 * for the given email. Does not touch the User table or any end-user data.
 */
async function main() {
  const email = (process.env.ADMIN_SEED_EMAIL || 'superadmin@threadflank.com').toLowerCase();
  const password = process.env.ADMIN_SEED_PASSWORD || 'ChangeMe123!';

  const existing = await prisma.adminUser.findUnique({ where: { email } });
  if (existing) {
    console.log(`[seed] AdminUser ${email} already exists — skipping admin creation.`);
  } else {
    const hashedPassword = await bcrypt.hash(password, 10);

    await prisma.adminUser.create({
      data: {
        email,
        password: hashedPassword,
        name: 'Super Admin',
        role: AdminRole.SUPER_ADMIN,
      },
    });

    console.log(`[seed] Created SUPER_ADMIN ${email}.`);
    if (!process.env.ADMIN_SEED_PASSWORD) {
      console.warn('[seed] ADMIN_SEED_PASSWORD was not set — used the default password. Change it via POST /api/admin-panel/auth/reset-password before going live.');
    }
  }

  // ─── Seed Default Legal CMS Content Blocks ──────────────────────────────────
  await seedCmsBlocks();
}

async function seedCmsBlocks() {
  const legalBlocks = [
    {
      key: 'terms',
      type: 'LEGAL' as any,
      title: 'Terms & Conditions',
      status: 'PUBLISHED' as any,
      publishedAt: new Date(),
      body: {
        intro: 'These terms govern your use of Threadflank: the website, the Drape studio, the wardrobe, the twin circle, the brand feed and messaging. By creating an account you agree to them.',
        sections: [
          {
            heading: '1. Your account',
            body: [
              "You must be at least 16 years old to create an account. Keep your password private; you're responsible for activity on your account.",
              'Give accurate information when you sign up. We may suspend accounts that break these terms or put other people at risk.',
            ],
          },
          {
            heading: '2. Your twin and your photos',
            body: [
              'You own the photos you upload and the body details you enter. You give us a limited licence to store and process them only to provide the service — building your twin, rendering try-ons and showing your saved looks.',
              "Only upload photos of yourself, or of people who have clearly agreed. Don't upload images of anyone under 16 without their parent or guardian's consent.",
            ],
          },
          {
            heading: '3. Acceptable use',
            body: [
              "Don't use the service to create sexual, harassing, deceptive or defamatory images of anyone, to impersonate a real person, or to undress or alter a person's body without consent.",
              "Don't scrape the service, reverse-engineer the models, or try to get around usage limits or plan restrictions.",
            ],
          },
          {
            heading: '4. AI-generated looks',
            body: [
              "Try-ons, combinations and styling suggestions are generated by AI. They're a visual guide, not a promise of how a garment will fit, drape or look in real life.",
              'You may share looks you create for personal, non-commercial use. Brand imagery remains the property of the brand.',
            ],
          },
          {
            heading: '5. Liability & Changes',
            body: [
              "Threadflank is provided 'as is'. To the extent the law allows, we aren't liable for indirect losses, or for purchases handled by third-party stores.",
              "We may update these terms. Significant changes will be communicated in the app or via email.",
            ],
          },
        ],
      },
    },
    {
      key: 'privacy',
      type: 'LEGAL' as any,
      title: 'Privacy Policy',
      status: 'PUBLISHED' as any,
      publishedAt: new Date(),
      body: {
        intro: 'We value your privacy. This policy explains what personal data Threadflank collects, why we collect it, how it is protected, and your rights over your data.',
        sections: [
          {
            heading: '1. Information We Collect',
            body: [
              'Account details: Email address, username, optional profile details (avatar, bio, phone, location).',
              'Digital Twin data: Selfies and photos you upload, body measurements (height, weight, age, skin tone), and generated avatar models.',
              'Activity & Usage: Wardrobe items, saved looks, try-on history, and interactions with brand posts and messages.',
            ],
          },
          {
            heading: '2. How We Use Your Information',
            body: [
              'To generate and render high-fidelity digital try-on models.',
              'To personalize styling recommendations, occasion plans, and feed content.',
              'To facilitate messaging and friend interactions within your permission settings.',
              'We do NOT sell your photos, personal information, or biometric representations to third parties.',
            ],
          },
          {
            heading: '3. AI Processing & Third-Party APIs',
            body: [
              'Photos uploaded for virtual try-on are securely processed by our AI inference pipelines solely for the purpose of garment draping.',
              'Images are retained in encrypted storage to power your persistent twin and can be deleted by you at any time.',
            ],
          },
          {
            heading: '4. Your Data Rights & Deletion',
            body: [
              'You have the right to access, update, export, or delete your personal data.',
              'You can delete your photos or entire account at any time via your account settings or by contacting privacy@threadflank.com.',
              'Upon deletion request, your uploaded photos and generated twins are permanently purged within 30 days.',
            ],
          },
          {
            heading: '5. Contacting Privacy Support',
            body: [
              'If you have questions about this Privacy Policy or wish to exercise data rights, reach out to us at privacy@threadflank.com.',
            ],
          },
        ],
      },
    },
    {
      key: 'disclaimer',
      type: 'LEGAL' as any,
      title: 'Disclaimer',
      status: 'PUBLISHED' as any,
      publishedAt: new Date(),
      body: {
        intro: 'Threadflank helps you picture outfits before you wear or buy them. Please read how far that picture can be trusted.',
        sections: [
          {
            heading: '1. AI try-on is an approximation',
            body: [
              'Draped looks are generated by AI from your photo, your body details and an image of the garment. Colour, texture, fit, length and drape can differ from the real item — especially with loose, sheer, embellished or layered garments like sarees, lehengas and dupattas.',
              "Screen settings and lighting also change how colours look. Always check the brand's size guide and product photos before buying.",
            ],
          },
          {
            heading: '2. Not sizing or body advice',
            body: [
              "Height, weight and skin-tone fields are used only to make renders more consistent. They are not a measurement service and we don't give health, fitness or body-image advice.",
            ],
          },
          {
            heading: '3. Styling suggestions',
            body: [
              "AI combinations and occasion plans are suggestions based on what's in your wardrobe. They may not suit every dress code, culture or venue — use your own judgement.",
            ],
          },
          {
            heading: '4. Brands and third-party stores',
            body: [
              "Brand content in the feed is provided by the brands. We don't sell clothes or guarantee prices, stock, delivery or quality, and we're not responsible for purchases made on external websites.",
            ],
          },
        ],
      },
    },
  ];

  for (const block of legalBlocks) {
    const existing = await prisma.contentBlock.findUnique({ where: { key: block.key } });
    if (!existing) {
      await prisma.contentBlock.create({ data: block });
      console.log(`[seed] Created CMS block: ${block.key}`);
    } else {
      console.log(`[seed] CMS block ${block.key} already exists.`);
    }
  }
}

main()
  .catch((error) => {
    console.error('[seed] Failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
